# Fabric Properties
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.9

# Mod Properties
mod_id=elyby_wardrobe
mod_name=Ely.by Wardrobe & Custom Capes
mod_version=1.0.0
mod_group=com.elyby.wardrobe
archives_base_name=elyby-wardrobe

# JVM properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
